name: React CI # workflow 이름

on: # 이벤트 정의
  push:
    branches: ["main"] # chori 브랜치에 push 이벤트

jobs:
  build:
    runs-on: ubuntu-latest # job을 수행하는 OS

    steps: # job에서 수행하는 step 정의
      # Repository에서 CI 수행 서버로 코드를 내려받는 action
      - name: Checkout source code
        uses: actions/checkout@v4

      # Node.js 설치
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 의존 파일 설치
      - name: Install dependencies
        run: npm install

      # 리액트 빌드
      - name: Build React app
        run: npm run build

      # 이미지 빌드 및 도커 허브에 push
      - name: Build docker image and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/miracle-morning-front .
          docker push ${{ secrets.DOCKER_USERNAME }}/miracle-morning-front
